# Configuración de base de datos MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/map_electric?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:josias}
spring.datasource.password=${DB_PASSWORD:Josias@2026!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de puerto (Render asigna el puerto automáticamente mediante la variable PORT)
server.port=${PORT:8080}
server.address=0.0.0.0

# JWT Secret (Debe ser una cadena larga y segura)
jwt.secret=${JWT_SECRET:mi_clave_secreta_super_segura_para_electrical_map_2024_pro_max}
jwt.expiration=${JWT_EXPIRATION:86400000}

# XD